config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  authenticated :user do
    root 'groups#index', as: :authenticated_root
  end
  unauthenticated do
    root "splash#splash", as: :unauthenticated_root
  end

  resources :groups do
    resources :items
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/entity.rb
class Entity < ApplicationRecord
  belongs_to :user
  has_many :groups_entities, dependent: :destroy
  has_and_belongs_to_many :groups

  validates :name, presence: true
  validates :amount, presence: true, numericality: { greater_than: 0 }

  def self.show_trans
    order(created_at: :desc)
  end

  def self.calculate_sum
    sum(:amount)
  end
end

app/models/group.rb
class Group < ApplicationRecord
  belongs_to :user
  has_many :groups_item
  # has_and_belongs_to_many :entities, join_table: 'groups_entities'
  has_many :items, through: :groups_item

  validates :name, presence: true
  validates :icon, presence: true

  def self.display_groups
    order(created_at: :desc)
  end

  def total_value
    items.sum(:amount)
  end
end

app/models/groups_item.rb
class GroupsItem < ApplicationRecord
  belongs_to :group
  belongs_to :item
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :author, class_name: 'User'
  has_many :groups_items, dependent: :destroy
  has_many :groups, through: :groups_items

  validates :name, presence: true
  validates :amount, presence: true, numericality: { greater_than: 0 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :groups
  has_many :items, foreign_key: 'author_id', dependent: :destroy

  validates :name, :email, :password, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    attributes = [:name]
    devise_parameter_sanitizer.permit(:sign_up, keys: attributes)
    devise_parameter_sanitizer.permit(:account_update, keys: attributes)
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :authenticate_user!

  def index
    @groups = current_user.groups.display_groups
  end

  def new
    @group = current_user.groups.build
  end

  def show; end

  def create
    @group = current_user.groups.build(group_params)

    if @group.save
      redirect_to groups_path
    else
      render :new, status: 422
    end
  end

  private

  def group_params
    params.require(:group).permit(:user_id, :name, :icon)
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_group

  def index
    @items = Group.find(@group.id).items.order(created_at: :desc)
  end

  def new
    @group = Group.find(params[:group_id])
    @item = @group.items.build
  end

  def create
    @group = Group.find(params[:group_id])
    @items = @group.items.build(item_params)
    @items.author = current_user

    Rails.logger.info @item.inspect

    if @items.save
      redirect_to group_items_path(@group), notice: 'Transaction successful.'
    else
      render :new
    end
  end

  private

  def item_params
    params.require(:item).permit(:name, :amount, :group_ids)
  end

  def set_group
    @group = current_user.groups.find(params[:group_id])
  end
end

app/controllers/splash_controller.rb
class SplashController < ApplicationController
  def splash; end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index; end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/splash_helper.rb
module SplashHelper
end

app/views/entities/new.html.erb
<h1>Add new Transaction</h1>
<% if @entity.errors.any? %>
  <div class="post-errors-box">
    <p><%= pluralize(@group.errors.count, "error") %> found:</p>

    <ul>
      <% @entity.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
<% end %>

<%= form_with url: "/groups/#{params[:group_id]}/entities", model: @entity, method: :post do |form| %>
<div class="d-flex flex-column">
  <div class="col mb-3">
  <%= form.label :name%>
  <%= form.text_field :name%>
  </div>
  <div class="col mb-3">
  <%= form.label :amount%>
  <%= form.text_field :amount%>
  </div>
  <div class="col mb-3">
  <%= form.label :groups_ids %>
  <%= form.collection_select :group_ids, Group.all, :id, :name, {} %>
  </div>
  <div class="col mb-3 ms-2">
  <%= form.submit 'Save', class: "btn btn-primary" %>
  </div>
</div>
<% end %>

<%= link_to 'Back', group_entities_path, class: "btn btn-danger ms-2" %>

app/views/groups/index.html.erb
<%= render 'shared/navbar', title: "#{@groups.name}", back_link: false %>
<div class = "groups_container">
  <% @groups.each do |group| %>
    <div class =  "group">
    <%= link_to group_items_path(group), class: 'cont' do %>
      <div class = "details_container d-flex justify-content-around">
      <img src="<%= group.icon %>" alt="group Icon" class="group-icon">
        <h2><%= group.name %><h2>
        <h3>$<%= group.total_value %></h3>
      </div>
      <div class = "group_actions">
      <p class="date"><%= "#{group.created_at.day} #{group.created_at.strftime("%b")} #{group.created_at.year}" %></p>
      </div>
    </div>
  <% end %>
  <% end %>
</div>

<div class="add-btn">
  <%= link_to "Add New Group", new_group_path, class: 'add-link' %>
</div>

app/views/groups/new.html.erb
<%= render 'shared/navbar', back_link: groups_path, title:"New Category" %>

<%=form_for @group, html: {class:""} do |f| %>
  <div class="input-field">
    <%= f.text_field :name, placeholder: 'Name', class: 'i-control' %>
  </div>

  <div class="input-field">
    <%= f.url_field :icon, class: 'i-control', placeholder: "URL"%>
  </div>

  <div class="add-btn">
    <%= f.submit %>
  </div>
<% end %>

app/views/items/index.html.erb
<%= render 'shared/navbar', back_link: groups_path, title:"TRANSACTION" %>

<div class="category-section">
  <div class="category-header">
    <div class="category-header-title">
      <div class="cat-detail">
        <div class="category-icon">
        <img src="<%= @group.icon %>" alt="group Icon" class="group-icon">
        </div>  
        <div class="category-name">
          <%= @group.name %>
        </div>
      </div>
    </div>

    <div class="category-amount">
    $ <%= @group.items.sum(:amount) %>
  </div>
  </div>

  <div class="items-list">
    <% @items.each do |item| %>
        <div class="item-section">
          <div class="item-name">
            Transaction <%= item.name %>
          </div>
          <div class="item-amount">
            <p><%= "#{item.created_at.day} #{item.created_at.strftime("%b")} #{item.created_at.year} at #{item.created_at.strftime('%H:%M:%S')}" %></p>
          </div>
        </div>
    <% end %>
  </div>

  <div class="add-btn">
    <%= link_to 'ADD TRANSACTION', new_group_item_path(@group), class: "add-link" %>
  </div>
</div>

app/views/items/new.html.erb
<%= render 'shared/navbar', back_link: group_items_path, title: "New Transaction" %>

<%= form_with model: [@group, @item], class:"add-form" do |form| %>

<div class="form-fields">
  <div class="input-field">
    <%= form.text_field :name, class: "i-control", placeholder: 'Name' %>
    <% if @item.errors.has_key?(:name) %>
        <p class="error-message"><%= @item.errors[:name].first %></p>
      <% end %>
  </div>

  <div class="input-field">
    <%= form.number_field :amount, class: "i-control", placeholder: 'Amount' %>
    <% if @item.errors.has_key?(:amount) %>
        <p class="error-message"><%= @item.errors[:amount].first %></p>
      <% end %>
  </div>

  <div class="input-field">
    <%= form.collection_select :group_ids, Group.all, :id, :name, {}, class: "form-select i-control" %>
     <% if @item.errors.has_key?(:group_ids) %>
        <p class="error-message"><%= @item.errors[:group_ids].first %></p>
      <% end %>
  </div>
  </div>

  <div class="add-btn">
  <%= form.submit "Save" %>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BudgetApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/shared/_navbar.html.erb
<header class="main-header">
  <% if back_link %>
    <a href="<%= back_link %>" class="icon-btn">
      <i class="fa fa-arrow-left fa-lg"></i>
    </a>
  <% else %>
    <!-- Add a button to trigger the offcanvas menu -->
      <button type="button" class="icon-btn" id="toggleMenu">
    <i class="fa fa-bars"></i>
  </button>
  <% end %>
  <h1><%= title.upcase %></h1>
  <% if user_signed_in? %>
    <%= button_to destroy_user_session_path, method: :delete, class: "icon text-end" do %>
      <i class="fa fa-user"></i> Logout
    <% end %>
  <% elsif controller_name != 'sessions' %>
    <%= link_to new_user_session_path, class: "icon text-end" do %>
      <div>Next</div>
    <% end %>
  <% else %>
    <%= link_to new_user_registration_path, class: "icon text-end" do %>
      <i class="fa fa-user-plus"></i>
    <% end %>
  <% end %>
</header>

<% if user_signed_in? %>
<div class="offcanvas" id="offcanvasMenu">
      <button type="button" class="close-btn" id="closeMenu" aria-label="Close">x</button>
    <div class="offcanvas-header">
      <h2 class="offcanvas-title" id="sidebarLabel">Budget App</h2>
    </div>
    <div class="offcanvas-body">
      <div class="profile">
        <span>User: <%= current_user.name %></span>
      </div>
      <div class="actions">
      <i class="fa fa-cogs" aria-hidden="true"> <%= link_to "Account Settings", edit_user_registration_path, class: "action" %></i>
        <hr>
        <i class="fa fa-plus-circle" aria-hidden="true"> <%= link_to "Create Group", new_group_path, class: "action" %></i>
        <hr>
        <i class="fa fa-plus-circle" aria-hidden="true"> <a href="#" class="action">Create Transaction</a></i>
        <hr>
        <i class="fa fa-user" aria-hidden="true"> <a href="#" target="_blank" class="action">Author Profile</a></i>
      </div>
    </div>
  </div>
<% end %>

<script>
  document.getElementById('toggleMenu').addEventListener('click', function() {
    document.getElementById('offcanvasMenu').classList.toggle('show');
  });

  document.getElementById('closeMenu').addEventListener('click', function() {
    document.getElementById('offcanvasMenu').classList.remove('show');
  });
</script>

app/views/splash/splash.html.erb
<div class="splash">
  <h1 class='s-title'>My Budget App</h1>

<div class='btn-cont'>
<a href="<%= new_user_session_path %>" class="log-btn">Login</a>
<a href="<%= new_user_registration_path %>" class="sign-btn">Sign Up</a>
</div>
</div>